// Generated by scripts/generate_typescript.py. Do not edit by hand.

export namespace RecipeflowAnalysisV1Schema {
  export interface FlowFeature {
    readonly id: string;
    readonly related_ids?: ReadonlyArray<string>;
  }

  export interface MaterialUsage {
    readonly consumer_operation_ids?: ReadonlyArray<string>;
    readonly material_id: string;
    readonly producer_operation_id?: string | null;
  }

  export interface SetupPrerequisite {
    readonly operation_id: string;
    readonly required_by_operation_ids?: ReadonlyArray<string>;
  }

  export interface GraphAnalysis {
    readonly branches?: ReadonlyArray<FlowFeature>;
    readonly critical_path_minutes?: number | null;
    readonly critical_path_operation_ids?: ReadonlyArray<string>;
    readonly disconnected_components?: ReadonlyArray<ReadonlyArray<string>>;
    readonly final_ids: ReadonlyArray<string>;
    readonly garnish_ids?: ReadonlyArray<string>;
    readonly ingredient_count: number;
    readonly intermediate_ids: ReadonlyArray<string>;
    readonly joins?: ReadonlyArray<FlowFeature>;
    readonly material_count: number;
    readonly material_usage?: ReadonlyArray<MaterialUsage>;
    readonly operation_count: number;
    readonly parallel_operation_groups?: ReadonlyArray<ReadonlyArray<string>>;
    readonly reserved_ids?: ReadonlyArray<string>;
    readonly schema_version?: "recipeflow.analysis/v1";
    readonly setup_count: number;
    readonly setup_prerequisites?: ReadonlyArray<SetupPrerequisite>;
    readonly splits?: ReadonlyArray<FlowFeature>;
    readonly topological_operation_ids: ReadonlyArray<string>;
    readonly unused_ingredient_ids: ReadonlyArray<string>;
    readonly waste_ids?: ReadonlyArray<string>;
  }
}

export namespace RecipeflowCliResultV1Schema {
  export interface Diagnostic {
    readonly code: string;
    readonly context?: Readonly<Record<string, unknown>>;
    readonly fix?: DiagnosticFix | null;
    readonly message: string;
    readonly path?: string;
    readonly related_paths?: ReadonlyArray<string>;
    readonly schema_version?: "recipeflow.diagnostic/v1";
    readonly severity: Severity;
    readonly suggestions?: ReadonlyArray<string>;
  }

  export interface DiagnosticFix {
    readonly description?: string | null;
    readonly operation: "add" | "remove" | "replace";
    readonly path: string;
    readonly value?: unknown | null;
  }

  export type Severity = "error" | "warning" | "info";

  export interface CliResult {
    readonly command: string;
    readonly data?: unknown | null;
    readonly diagnostics?: ReadonlyArray<Diagnostic>;
    readonly ok: boolean;
    readonly schema_version?: "recipeflow.cli-result/v1";
  }
}

export namespace RecipeflowDiagnosticV1Schema {
  export interface DiagnosticFix {
    readonly description?: string | null;
    readonly operation: "add" | "remove" | "replace";
    readonly path: string;
    readonly value?: unknown | null;
  }

  export type Severity = "error" | "warning" | "info";

  export interface Diagnostic {
    readonly code: string;
    readonly context?: Readonly<Record<string, unknown>>;
    readonly fix?: DiagnosticFix | null;
    readonly message: string;
    readonly path?: string;
    readonly related_paths?: ReadonlyArray<string>;
    readonly schema_version?: "recipeflow.diagnostic/v1";
    readonly severity: Severity;
    readonly suggestions?: ReadonlyArray<string>;
  }
}

export namespace RecipeflowDocumentV1Schema {
  export interface Ambiguity {
    readonly alternatives?: ReadonlyArray<string>;
    readonly description: string;
    readonly explicit?: boolean;
    readonly resolution?: string | null;
  }

  export interface DurationSpec {
    readonly maximum_minutes?: string | null;
    readonly minimum_minutes?: string | null;
    readonly source_text: string;
  }

  export interface Ingredient {
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly annotations?: ReadonlyArray<string>;
    readonly label: string;
    readonly optional?: boolean;
    readonly preparation_state?: string | null;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly quantity?: string | Quantity | null;
    readonly role?: MaterialRole;
    readonly source_text?: string | null;
    readonly temperature_state?: string | null;
    readonly unit?: string | null;
  }

  export type MaterialRole = "ingredient" | "intermediate" | "final" | "garnish" | "waste" | "reserved" | "optional";

  export interface MaterialUse {
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly from_reserve?: boolean;
    readonly material: string;
    readonly optional?: boolean;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly quantity?: string | Quantity | null;
    readonly reserve?: boolean;
    readonly source_text?: string | null;
  }

  export interface NormalizedQuantity {
    readonly maximum?: string | null;
    readonly minimum?: string | null;
    readonly unit?: string | null;
    readonly value?: string | null;
  }

  export interface Operation {
    readonly action: string;
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly completion_criteria?: string | null;
    readonly duration?: string | DurationSpec | null;
    readonly equipment?: ReadonlyArray<string>;
    readonly id?: string | null;
    readonly inputs?: ReadonlyArray<string | MaterialUse>;
    readonly label?: string | null;
    readonly notes?: ReadonlyArray<string>;
    readonly operation_type?: string | null;
    readonly optional?: boolean;
    readonly outputs: Readonly<Record<string, OutputDeclaration>>;
    readonly precedes?: ReadonlyArray<string>;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly repeat?: RepeatSpec | null;
    readonly requires?: ReadonlyArray<string>;
    readonly resources?: ReadonlyArray<ResourceRequirement>;
    readonly subrecipe?: SubrecipeRef | null;
    readonly temperature?: string | TemperatureSpec | null;
    readonly until?: string | null;
  }

  export interface OutputDeclaration {
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly annotations?: ReadonlyArray<string>;
    readonly final?: boolean;
    readonly label: string;
    readonly optional?: boolean;
    readonly preparation_state?: string | null;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly quantity?: string | Quantity | null;
    readonly role?: MaterialRole;
    readonly shareable?: boolean;
    readonly source_text?: string | null;
    readonly temperature_state?: string | null;
    readonly unit?: string | null;
  }

  export interface Provenance {
    readonly confidence?: string | null;
    readonly note?: string | null;
    readonly path?: string | null;
    readonly source_id?: string | null;
    readonly source_text?: string | null;
  }

  export interface Quantity {
    readonly normalized?: NormalizedQuantity | null;
    readonly source_text: string;
  }

  export interface RecipeMetadata {
    readonly allow_multiple_outputs?: boolean;
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly author?: string | null;
    readonly description?: string | null;
    readonly id?: string | null;
    readonly locale?: string | null;
    readonly notes?: ReadonlyArray<string>;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly source?: SourceRef | null;
    readonly tags?: ReadonlyArray<string>;
    readonly title: string;
    readonly yield?: string | null;
  }

  export interface RepeatSpec {
    readonly count?: number | null;
    readonly interval?: string | DurationSpec | null;
    readonly until?: string | null;
  }

  export interface ResourceRequirement {
    readonly exclusive?: boolean;
    readonly id: string;
    readonly label?: string | null;
    readonly quantity?: number;
  }

  export interface SetupAction {
    readonly action: string;
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly duration?: string | DurationSpec | null;
    readonly equipment?: ReadonlyArray<string>;
    readonly id?: string | null;
    readonly label?: string | null;
    readonly notes?: ReadonlyArray<string>;
    readonly produces?: string | null;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly requires?: ReadonlyArray<string>;
    readonly resources?: ReadonlyArray<ResourceRequirement>;
    readonly target?: string | null;
    readonly temperature?: string | TemperatureSpec | null;
  }

  export interface SourceRef {
    readonly author?: string | null;
    readonly id?: string | null;
    readonly notes?: ReadonlyArray<string>;
    readonly retrieved_at?: string | null;
    readonly title?: string | null;
    readonly url?: string | null;
  }

  export interface Subrecipe {
    readonly id: string;
    readonly ingredients?: Readonly<Record<string, Ingredient>>;
    readonly notes?: ReadonlyArray<string>;
    readonly operations?: ReadonlyArray<Operation>;
    readonly output_ids?: ReadonlyArray<string>;
    readonly setup?: ReadonlyArray<SetupAction>;
    readonly title: string;
  }

  export interface SubrecipeRef {
    readonly id: string;
    readonly inputs?: Readonly<Record<string, string>>;
    readonly output?: string | null;
    readonly scale?: string | null;
  }

  export interface TemperatureSpec {
    readonly maximum?: string | null;
    readonly minimum?: string | null;
    readonly source_text: string;
    readonly unit?: "C" | "F" | "K" | null;
    readonly value?: string | null;
  }

  export interface RecipeDocument {
    readonly ingredients: Readonly<Record<string, Ingredient>>;
    readonly operations: ReadonlyArray<Operation>;
    readonly recipe: RecipeMetadata;
    readonly recipeflow?: 1;
    readonly schema_version?: "recipeflow.document/v1";
    readonly setup?: ReadonlyArray<SetupAction>;
    readonly subrecipes?: Readonly<Record<string, Subrecipe>>;
  }
}

export namespace RecipeflowGraphV1Schema {
  export interface Ambiguity {
    readonly alternatives?: ReadonlyArray<string>;
    readonly description: string;
    readonly explicit?: boolean;
    readonly resolution?: string | null;
  }

  export interface CompiledSubrecipe {
    readonly edges: ReadonlyArray<Edge>;
    readonly final_material_ids: ReadonlyArray<string>;
    readonly id: string;
    readonly nodes: ReadonlyArray<MaterialNode | OperationNode>;
    readonly title: string;
  }

  export interface DurationSpec {
    readonly maximum_minutes?: string | null;
    readonly minimum_minutes?: string | null;
    readonly source_text: string;
  }

  export interface Edge {
    readonly id: string;
    readonly kind: EdgeKind;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly quantity?: string | null;
    readonly source: string;
    readonly source_path?: string | null;
    readonly target: string;
  }

  export type EdgeKind = "consumes" | "produces" | "precedes" | "requires" | "reserves" | "discards" | "optionally-applies";

  export interface MaterialNode {
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly annotations?: ReadonlyArray<string>;
    readonly id: string;
    readonly kind?: "material";
    readonly label: string;
    readonly normalized_quantity?: Quantity | null;
    readonly optional?: boolean;
    readonly preparation_state?: string | null;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly quantity?: string | null;
    readonly role: MaterialRole;
    readonly source_path?: string | null;
    readonly source_text?: string | null;
    readonly temperature_state?: string | null;
    readonly unit?: string | null;
  }

  export type MaterialRole = "ingredient" | "intermediate" | "final" | "garnish" | "waste" | "reserved" | "optional";

  export interface NormalizedQuantity {
    readonly maximum?: string | null;
    readonly minimum?: string | null;
    readonly unit?: string | null;
    readonly value?: string | null;
  }

  export interface OperationNode {
    readonly action: string;
    readonly ambiguity?: ReadonlyArray<Ambiguity>;
    readonly duration?: string | null;
    readonly duration_value?: DurationSpec | null;
    readonly equipment?: ReadonlyArray<string>;
    readonly id: string;
    readonly kind?: "operation";
    readonly label: string;
    readonly notes?: ReadonlyArray<string>;
    readonly operation_kind: "setup" | "transform";
    readonly operation_type?: string | null;
    readonly optional?: boolean;
    readonly provenance?: ReadonlyArray<Provenance>;
    readonly repeat?: RepeatSpec | null;
    readonly resources?: ReadonlyArray<ResourceRequirement>;
    readonly source_path?: string | null;
    readonly subrecipe_id?: string | null;
    readonly subrecipe_inputs?: ReadonlyArray<SubrecipeInputBinding>;
    readonly subrecipe_output?: string | null;
    readonly subrecipe_scale?: string | null;
    readonly target?: string | null;
    readonly temperature?: string | null;
    readonly temperature_value?: TemperatureSpec | null;
    readonly until?: string | null;
  }

  export interface Provenance {
    readonly confidence?: string | null;
    readonly note?: string | null;
    readonly path?: string | null;
    readonly source_id?: string | null;
    readonly source_text?: string | null;
  }

  export interface Quantity {
    readonly normalized?: NormalizedQuantity | null;
    readonly source_text: string;
  }

  export interface RepeatSpec {
    readonly count?: number | null;
    readonly interval?: string | DurationSpec | null;
    readonly until?: string | null;
  }

  export interface ResourceRequirement {
    readonly exclusive?: boolean;
    readonly id: string;
    readonly label?: string | null;
    readonly quantity?: number;
  }

  export interface SourceRef {
    readonly author?: string | null;
    readonly id?: string | null;
    readonly notes?: ReadonlyArray<string>;
    readonly retrieved_at?: string | null;
    readonly title?: string | null;
    readonly url?: string | null;
  }

  export interface SubrecipeInputBinding {
    readonly input_id: string;
    readonly material_id: string;
    readonly source_path: string;
  }

  export interface TemperatureSpec {
    readonly maximum?: string | null;
    readonly minimum?: string | null;
    readonly source_text: string;
    readonly unit?: "C" | "F" | "K" | null;
    readonly value?: string | null;
  }

  export interface RecipeGraph {
    readonly description?: string | null;
    readonly edges: ReadonlyArray<Edge>;
    readonly final_material_ids: ReadonlyArray<string>;
    readonly locale?: string | null;
    readonly nodes: ReadonlyArray<MaterialNode | OperationNode>;
    readonly recipe_id: string;
    readonly schema_version?: "recipeflow.graph/v1";
    readonly source?: SourceRef | null;
    readonly subrecipes?: Readonly<Record<string, CompiledSubrecipe>>;
    readonly tags?: ReadonlyArray<string>;
    readonly title: string;
    readonly yield_text?: string | null;
  }
}

export namespace RecipeflowRenderResultV1Schema {
  export interface RenderArtifact {
    readonly content: string;
    readonly format: string;
    readonly height?: number | null;
    readonly media_type: string;
    readonly schema_version?: "recipeflow.render-result/v1";
    readonly width?: number | null;
  }
}

export namespace RecipeflowTabularLayoutV1Schema {
  export interface Diagnostic {
    readonly code: string;
    readonly context?: Readonly<Record<string, unknown>>;
    readonly fix?: DiagnosticFix | null;
    readonly message: string;
    readonly path?: string;
    readonly related_paths?: ReadonlyArray<string>;
    readonly schema_version?: "recipeflow.diagnostic/v1";
    readonly severity: Severity;
    readonly suggestions?: ReadonlyArray<string>;
  }

  export interface DiagnosticFix {
    readonly description?: string | null;
    readonly operation: "add" | "remove" | "replace";
    readonly path: string;
    readonly value?: unknown | null;
  }

  export interface Insets {
    readonly bottom?: number;
    readonly left?: number;
    readonly right?: number;
    readonly top?: number;
  }

  export interface Lane {
    readonly height?: number;
    readonly index: number;
    readonly initial_material_id?: string | null;
    readonly y: number;
  }

  export interface LayoutBox {
    readonly collision_group?: string;
    readonly corner_radius?: number;
    readonly id: string;
    readonly kind: "title" | "ingredient" | "setup" | "operation" | "material-label" | "final-output" | "annotation";
    readonly opaque?: boolean;
    readonly rect: Rect;
    readonly style_class: string;
    readonly text_block_ids?: ReadonlyArray<string>;
  }

  export interface MaterialSegment {
    readonly label: string;
    readonly label_box_id?: string | null;
    readonly lane: number;
    readonly material_id: string;
    readonly path_id?: string | null;
    readonly quantity?: string | null;
    readonly role: "ingredient" | "intermediate" | "final" | "waste" | "garnish" | "reserved" | "optional";
    readonly show_inline_label?: boolean;
    readonly show_left_label?: boolean;
    readonly x1: number;
    readonly x2: number;
    readonly y: number;
  }

  export interface OperationCell {
    readonly action: string;
    readonly box_ids?: ReadonlyArray<string>;
    readonly duration?: string | null;
    readonly input_material_ids?: ReadonlyArray<string>;
    readonly label: string;
    readonly operation_id: string;
    readonly orientation?: "horizontal" | "vertical";
    readonly output_material_ids?: ReadonlyArray<string>;
    readonly rect?: Rect | null;
    readonly temperature?: string | null;
    readonly text_block_ids?: ReadonlyArray<string>;
    readonly until?: string | null;
    readonly x: number;
    readonly y1: number;
    readonly y2: number;
  }

  export interface Point {
    readonly x: number;
    readonly y: number;
  }

  export interface Rect {
    readonly height: number;
    readonly width: number;
    readonly x: number;
    readonly y: number;
  }

  export interface RoutedPath {
    readonly id: string;
    readonly kind: "material" | "setup-dependency" | "guide";
    readonly points: ReadonlyArray<Point>;
    readonly source_id?: string | null;
    readonly stroke_width?: number;
    readonly style_class: string;
    readonly target_ids?: ReadonlyArray<string>;
  }

  export interface SetupCard {
    readonly detail?: string | null;
    readonly height?: number;
    readonly label: string;
    readonly operation_id: string;
    readonly rect?: Rect | null;
    readonly required_by_operation_ids?: ReadonlyArray<string>;
    readonly text_block_ids?: ReadonlyArray<string>;
    readonly width: number;
    readonly x: number;
    readonly y?: number;
  }

  export type Severity = "error" | "warning" | "info";

  export interface TextBlock {
    readonly horizontal_alignment?: "start" | "center" | "end";
    readonly id: string;
    readonly lines: ReadonlyArray<WrappedLine>;
    readonly overflow?: boolean;
    readonly padding?: Insets;
    readonly parent_id?: string | null;
    readonly rect: Rect;
    readonly role: "title" | "recipe-yield" | "ingredient-quantity" | "ingredient-label" | "ingredient-source" | "ingredient-preparation" | "ingredient-annotation" | "ingredient-provenance" | "setup-label" | "setup-target" | "setup-required-by" | "setup-detail" | "setup-note" | "setup-provenance" | "operation-action" | "operation-input-quantity" | "operation-detail" | "operation-until" | "allocation-balance" | "material-label" | "final-label" | "annotation";
    readonly rotation?: -90 | 0;
    readonly source_text: string;
    readonly style: TextStyle;
    readonly vertical_alignment?: "top" | "middle" | "bottom";
  }

  export interface TextStyle {
    readonly fill?: string;
    readonly font_fallbacks?: ReadonlyArray<string>;
    readonly font_family?: string;
    readonly font_size?: number;
    readonly font_weight?: number;
    readonly line_height?: number;
  }

  export interface WrappedLine {
    readonly ascent: number;
    readonly baseline_y: number;
    readonly descent: number;
    readonly text: string;
    readonly width: number;
    readonly x: number;
  }

  export interface TabularLayout {
    readonly boxes?: ReadonlyArray<LayoutBox>;
    readonly diagnostics?: ReadonlyArray<Diagnostic>;
    readonly final_material_ids?: ReadonlyArray<string>;
    readonly header_height: number;
    readonly height: number;
    readonly label_width: number;
    readonly lanes: ReadonlyArray<Lane>;
    readonly materials: ReadonlyArray<MaterialSegment>;
    readonly notation?: string;
    readonly operations: ReadonlyArray<OperationCell>;
    readonly paths?: ReadonlyArray<RoutedPath>;
    readonly reading_order?: ReadonlyArray<string>;
    readonly row_height: number;
    readonly safe_margin?: number;
    readonly schema_version?: "recipeflow.tabular-layout/v1";
    readonly setup?: ReadonlyArray<SetupCard>;
    readonly setup_height: number;
    readonly text_blocks?: ReadonlyArray<TextBlock>;
    readonly theme?: "classic" | "modern";
    readonly title: string;
    readonly width: number;
  }
}

export type GraphAnalysis = RecipeflowAnalysisV1Schema.GraphAnalysis;
export type CliResult = RecipeflowCliResultV1Schema.CliResult;
export type Diagnostic = RecipeflowDiagnosticV1Schema.Diagnostic;
export type RecipeDocument = RecipeflowDocumentV1Schema.RecipeDocument;
export type RecipeGraph = RecipeflowGraphV1Schema.RecipeGraph;
export type RenderArtifact = RecipeflowRenderResultV1Schema.RenderArtifact;
export type TabularLayout = RecipeflowTabularLayoutV1Schema.TabularLayout;
