"""Generate deterministic TypeScript declarations from committed JSON Schemas."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schemas"
OUTPUT = ROOT / "types" / "recipeflow-contracts.d.ts"
IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def pascal(value: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", value)
    return "".join(word[:1].upper() + word[1:] for word in words) or "Contract"


def property_name(value: str) -> str:
    return value if IDENTIFIER_RE.match(value) else json.dumps(value, ensure_ascii=False)


def literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return json.dumps(value, ensure_ascii=False)


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return pascal(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return " | ".join(literal(item) for item in schema["enum"])
    for keyword, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        if keyword in schema:
            items = [ts_type(item) for item in schema[keyword]]
            return separator.join(dict.fromkeys(items))

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(ts_type({"type": item}) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"ReadonlyArray<{ts_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        if schema.get("properties"):
            return object_literal(schema)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Readonly<Record<string, {ts_type(additional)}>>"
        return "Readonly<Record<string, unknown>>"
    return "unknown"


def object_members(schema: dict[str, Any], indent: str) -> list[str]:
    required = set(schema.get("required", ()))
    members: list[str] = []
    for name, subschema in sorted(schema.get("properties", {}).items()):
        optional = "" if name in required else "?"
        members.append(
            f"{indent}readonly {property_name(name)}{optional}: {ts_type(subschema)};"
        )
    additional = schema.get("additionalProperties")
    if isinstance(additional, dict):
        members.append(f"{indent}readonly [key: string]: {ts_type(additional)};")
    return members


def object_literal(schema: dict[str, Any]) -> str:
    members = object_members(schema, "  ")
    if not members:
        return "Readonly<Record<string, unknown>>"
    return "{\n" + "\n".join(members) + "\n}"


def declaration(name: str, schema: dict[str, Any], indent: str = "") -> list[str]:
    if schema.get("type") == "object" or "properties" in schema:
        lines = [f"{indent}export interface {name} {{"]
        lines.extend(object_members(schema, indent + "  "))
        lines.append(f"{indent}}}")
        return lines
    return [f"{indent}export type {name} = {ts_type(schema)};"]


def render() -> str:
    schemas = sorted(SCHEMA_DIR.glob("recipeflow-*-v1.schema.json"))
    lines = [
        "// Generated by scripts/generate_typescript.py. Do not edit by hand.",
        "",
    ]
    root_aliases: list[tuple[str, str]] = []
    for path in schemas:
        schema = json.loads(path.read_text(encoding="utf-8"))
        namespace = pascal(path.stem)
        root_name = pascal(str(schema.get("title", namespace)))
        lines.append(f"export namespace {namespace} {{")
        for name, subschema in sorted(schema.get("$defs", {}).items()):
            lines.extend(declaration(pascal(name), subschema, "  "))
            lines.append("")
        lines.extend(declaration(root_name, schema, "  "))
        lines.append("}")
        lines.append("")
        root_aliases.append((root_name, namespace))

    for root_name, namespace in root_aliases:
        lines.append(f"export type {root_name} = {namespace}.{root_name};")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()

    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            print("TypeScript declarations are stale; run scripts/generate_typescript.py")
            return 1
        print(f"TypeScript declaration check passed: {OUTPUT.relative_to(ROOT)}")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
